version: '3'

services:
  # Nginx proxy service
  nginx:
    build: ./.docker/nginx
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - client

  # NodeJs api
  api:
    build:
      context: api
      dockerfile: ../.docker/api/Dockerfile
    env_file: .env
    depends_on:
      - db
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  # Mongodb
  db:
    image: mongo:4.4.1-bionic
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./.docker/mongodb/db:/data/db

  # Nuxt client
  client:
    build:
      context: ./client
      dockerfile: ../.docker/client/Dockerfile
    env_file: .env
    depends_on:
      - api
    environment:
      NUXT_HOST: 0.0.0.0
      API_HOST: 0.0.0.0
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
