version: '3'

services:
  server:
    build:
      context: ./server
    env_file: .env
#    depends_on:
#      - db
#    environment:
#      - MONGO_USERNAME=$MONGO_USERNAME
#      - MONGO_PASSWORD=$MONGO_PASSWORD
#      - MONGO_HOSTNAME=db
#      - MONGO_PORT=$MONGO_PORT
#      - MONGO_DB=$MONGO_DB
    expose:
      - $SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules

#  db:
#    image: mongo:4.4.1-bionic
#    env_file: .env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
#      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
#    volumes:
#      - ./db:/data/db

  client:
    build:
      context: ./client
    env_file: .env
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      API_HOST: 0.0.0.0
      API_PORT: $SERVER_PORT
      BASE_URL: $BASE_URL
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    #    expose:
    #      - 3000
    ports:
      - $CLIENT_PORT:3000
